# This action automatically lints commits with pylint

name: Lint Python Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -  name: Checkout
         uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: 3.11
      - name: Install python and pylint
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install math
          pip install cmath

        
      - name: Lint files
        run: |
          find . -name '*.py' -exec pylint {} \;

      - name: Upload pylint results
        uses: actions/upload-artifact@v3
        with:
          name: pylint-results.txt
          path: pylint.txt
